# Generated by Django 5.0.7 on 2024-08-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComments',
            new_name='UserComment',
        ),
    ]
